### PR TITLE
pilot video + loop

### PR DESCRIPTION
**Pull request by laurentperrinet**

### CODE REVIEW

**Comment by laurentperrinet** [comment]
salut @MariemDiane ! 
tu peux me dire si tu arrives à exécuter `2023-02-23_averaging-videos_loop.ipynb` ?
à plus, @laurentperrinet

**Comment by MariemDiane** [comment]
Salut Laurent !
J'essaye depuis tout à l'heure mais je galère un peu: il y a un problème
dans la version de imagio que j'arrive à télécharger et à importer; j'ai
updater la dernière version mais ça refuser d'importer imageio.v3.
Voilà l'erreur:

---------------------------------------------------------------------------ImportError
                              Traceback (most recent call last)
Input In [11], in <cell line: 1>()----> 1 import imageio.v3 as iio

File /opt/anaconda3/lib/python3.9/site-packages/imageio/v3.py:3, in
<module>      1 import numpy as np----> 3 from .core.imopen import
imopen      6 def imread(uri, *, index=None, plugin=None,
extension=None, format_hint=None, **kwargs):      7     """Read an
ndimage from a URI.      8       9     Opens the given URI and reads
an ndimage from it. The exact behavior   (...)     39         The
ndimage located at the given URI.     40     """

File /opt/anaconda3/lib/python3.9/site-packages/imageio/core/imopen.py:4,
in <module>      1 from pathlib import Path      2 import
warnings----> 4 from ..config import known_plugins      5 from
..config.extensions import known_extensions      6 from .request
import (      7     SPECIAL_READ_URIS,      8     URI_FILENAME,
(...)     11     Request,     12 )

File /opt/anaconda3/lib/python3.9/site-packages/imageio/config/__init__.py:7,
in <module>      1 from .extensions import (      2
extension_list,      3     known_extensions,      4     FileExtension,
     5     video_extensions,      6 )----> 7 from .plugins import
known_plugins, PluginConfig      9 __all__ = [     10
"known_plugins",     11     "PluginConfig",   (...)     15
"video_extensions",     16 ]

File /opt/anaconda3/lib/python3.9/site-packages/imageio/config/plugins.py:3,
in <module>      1 import importlib----> 3 from
..core.legacy_plugin_wrapper import LegacyPlugin      6 class
PluginConfig:      7     """Plugin Configuration Metadata      8
9     This class holds the information needed to lazy-import plugins.
 (...)     50      51     """

File /opt/anaconda3/lib/python3.9/site-packages/imageio/core/legacy_plugin_wrapper.py:6,
in <module>      3 import numpy as np      5 from ..config import
known_extensions----> 6 from .request import InitializationError,
IOMode      7 from .v3_plugin_api import ImageProperties, PluginV3
10 def _legacy_default_index(format):
ImportError: cannot import name 'InitializationError' from
'imageio.core.request'
(/opt/anaconda3/lib/python3.9/site-packages/imageio/core/request.py)


Et sinon j'ai essayé en remplaçant imageio.v3 par imageio dans la
cellule d'après (frames = iio.imread(vname, plugin="pyav"))

 mais ça me sort cette erreur:

---------------------------------------------------------------------------ValueError
                               Traceback (most recent call last)
Input In [10], in <cell line: 3>()      1 # bulk read all frames
2 # Warning: large videos will consume a lot of memory (RAM)----> 3
frames = iio.imread(vname, plugin="pyav")

File /opt/anaconda3/lib/python3.9/site-packages/imageio/core/functions.py:265,
in imread(uri, format, **kwargs)

File /opt/anaconda3/lib/python3.9/site-packages/imageio/core/functions.py:181,
in get_reader(uri, format, mode, **kwargs)
ValueError: Could not find a format to read the specified file in
single-image mode


Voilà, je ne sais pas trop où est le problème :/


À bientôt,


Mariem

**Comment by laurentperrinet** [comment]
c'est très probable que tu n'aies pas pyav...

essaie un

conda install -c conda-forge av




<https://anaconda.org/conda-forge/av>
Av :<https://anaconda.org/conda-forge/av>
anaconda.org<https://anaconda.org/conda-forge/av>
        [apple-touch-icon.png] <https://anaconda.org/conda-forge/av>



On 24 Feb 2023, at 15:51, MariemDiane ***@***.***> wrote:


Salut Laurent !
J'essaye depuis tout à l'heure mais je galère un peu: il y a un problème
dans la version de imagio que j'arrive à télécharger et à importer; j'ai
updater la dernière version mais ça refuser d'importer imageio.v3.
Voilà l'erreur:

---------------------------------------------------------------------------ImportError
Traceback (most recent call last)
Input In [11], in <cell line: 1>()----> 1 import imageio.v3 as iio

File /opt/anaconda3/lib/python3.9/site-packages/imageio/v3.py:3, in
<module> 1 import numpy as np----> 3 from .core.imopen import
imopen 6 def imread(uri, *, index=None, plugin=None,
extension=None, format_hint=None, **kwargs): 7 """Read an
ndimage from a URI. 8 9 Opens the given URI and reads
an ndimage from it. The exact behavior (...) 39 The
ndimage located at the given URI. 40 """

File /opt/anaconda3/lib/python3.9/site-packages/imageio/core/imopen.py:4,
in <module> 1 from pathlib import Path 2 import
warnings----> 4 from ..config import known_plugins 5 from
..config.extensions import known_extensions 6 from .request
import ( 7 SPECIAL_READ_URIS, 8 URI_FILENAME,
(...) 11 Request, 12 )

File /opt/anaconda3/lib/python3.9/site-packages/imageio/config/__init__.py:7,
in <module> 1 from .extensions import ( 2
extension_list, 3 known_extensions, 4 FileExtension,
5 video_extensions, 6 )----> 7 from .plugins import
known_plugins, PluginConfig 9 __all__ = [ 10
"known_plugins", 11 "PluginConfig", (...) 15
"video_extensions", 16 ]

File /opt/anaconda3/lib/python3.9/site-packages/imageio/config/plugins.py:3,
in <module> 1 import importlib----> 3 from
..core.legacy_plugin_wrapper import LegacyPlugin 6 class
PluginConfig: 7 """Plugin Configuration Metadata 8
9 This class holds the information needed to lazy-import plugins.
(...) 50 51 """

File /opt/anaconda3/lib/python3.9/site-packages/imageio/core/legacy_plugin_wrapper.py:6,
in <module> 3 import numpy as np 5 from ..config import
known_extensions----> 6 from .request import InitializationError,
IOMode 7 from .v3_plugin_api import ImageProperties, PluginV3
10 def _legacy_default_index(format):
ImportError: cannot import name 'InitializationError' from
'imageio.core.request'
(/opt/anaconda3/lib/python3.9/site-packages/imageio/core/request.py)


Et sinon j'ai essayé en remplaçant imageio.v3 par imageio dans la
cellule d'après (frames = iio.imread(vname, plugin="pyav"))

mais ça me sort cette erreur:

---------------------------------------------------------------------------ValueError
Traceback (most recent call last)
Input In [10], in <cell line: 3>() 1 # bulk read all frames
2 # Warning: large videos will consume a lot of memory (RAM)----> 3
frames = iio.imread(vname, plugin="pyav")

File /opt/anaconda3/lib/python3.9/site-packages/imageio/core/functions.py:265,
in imread(uri, format, **kwargs)

File /opt/anaconda3/lib/python3.9/site-packages/imageio/core/functions.py:181,
in get_reader(uri, format, mode, **kwargs)
ValueError: Could not find a format to read the specified file in
single-image mode


Voilà, je ne sais pas trop où est le problème :/


À bientôt,


Mariem

**Comment by MariemDiane** [comment]
Merci du tip, je vais essayer ça !

**Comment by laurentperrinet** [comment]
Ok et si ça marche pas tu peux pusher le notebook avec l’erreur



Le 27 févr. 2023 à 19:27, MariemDiane ***@***.***> a écrit :

﻿

Merci du tip, je vais essayer ça !

**Pull request merged**
